### ISSUE TITLE
vscode 运行此模板，提示未找到src/manifest.json文件，请问如何配置？

### ISSUE THREAD

**Issue by zuozonglin** [yang1206/uniapp-template#126]
如题：vscode 运行此模板，提示未找到src/manifest.json文件，请问如何配置？感谢

**Comment by yang1206** [comment]
安装依赖后，请先运行一下 `pnpm dev:mp-weixin`, 会自动生成manifest.json文件

**Comment by zuozonglin** [comment]
> 安装依赖后，请先运行一下 `pnpm dev:mp-weixin`, 会自动生成manifest.json文件

多谢了，已经可以了：
我是在windows下直接拖入vscode打开的。
我需要在src目录下面手动创建manifest.json空文件，然后再执行 `pnpm dev:mp-weixin` ，这样manifest.json文件内容会自动生成了。
