### ISSUE TITLE
dev error

### ISSUE THREAD

**Issue by canyuegongzi** [yang1206/uniapp-template#57]
(node:16212) UnhandledPromiseRejectionWarning: Error: Cannot find module 'node:path'

node version:  16

<img width="1190" alt="image" src="https://github.com/yang1206/uniapp-template/assets/32031360/4de33c5e-4544-4317-9753-69ec78077ada">

**Comment by canyuegongzi** [comment]
node 14  16 18 都试了，不行

**Comment by yang1206** [comment]
> node 14 16 18 都试了，不行

你好，我这里测试node16和node18都没有问题，有没有更多信息，你可以尝试全局搜素把`node:path`改成`path`试一下行不行

**Comment by canyuegongzi** [comment]
> > node 14 16 18 都试了，不行
> 
> 你好，我这里测试node16和node18都没有问题，有没有更多信息，你可以尝试全局搜素把`node:path`改成`path`试一下行不行

后来window 试了下，可以了，mac M2好像不行

**Comment by yang1206** [comment]
> > > node 14 16 18 都试了，不行
> > 
> > 
> > 你好，我这里测试node16和node18都没有问题，有没有更多信息，你可以尝试全局搜素把`node:path`改成`path`试一下行不行
> 
> 后来window 试了下，可以了，mac M2好像不行

我也是mac，你的node用过nvm之类的管理工具吗

**Comment by canyuegongzi** [comment]
> > > > node 14 16 18 都试了，不行
> > > 
> > > 
> > > 你好，我这里测试node16和node18都没有问题，有没有更多信息，你可以尝试全局搜素把`node:path`改成`path`试一下行不行
> > 
> > 
> > 后来window 试了下，可以了，mac M2好像不行
> 
> 我也是mac，你的node用过nvm之类的管理工具吗

有用nvm 管理工具

**Comment by yxl989458** [comment]
为啥我已保存代码 page.json就回去修改前了

**Comment by yang1206** [comment]
> 
@yxl989458 
https://github.com/uni-helper/vite-plugin-uni-pages
因为使用了这个插件，想要配置page.json你应该去配置根目录的page.ts文件，pages下的文件夹与文件会自动生成对应配置
