### ISSUE TITLE
Cannot read properties of null (reading 'split')

### ISSUE THREAD

**Issue by hootigger** [yang1206/uniapp-template#58]
搭建完成后,运行也正常,只要修改源文件,保存,热重载就会报这个错误!

**Comment by hootigger** [comment]
![image](https://github.com/yang1206/uniapp-template/assets/23418191/faa87db4-b086-4d30-be45-aaa2d260e9fc)

**Comment by yang1206** [comment]
排查出来了，应该是uniapp还没适配vite4.3，降级vite到4.2.x就ok了

**Comment by yang1206** [comment]
今天又看了一下，可能不是vite的锅，似乎和unocss和unocss-applet有关
