### ISSUE TITLE
pnpm dev:mp-alipay 编译产物在支付宝小程序开发者工具打开后报错

### ISSUE THREAD

**Issue by uglyp** [yang1206/uniapp-template#71]
## 请问是什么原因导致的
![lQLPJxQD8Qc1mLDNB-bNC0CwarET6cYljhwE2Z0ANYA6AA_2880_2022](https://github.com/yang1206/uniapp-template/assets/45615293/2f3ea1cb-bc72-4875-9daa-44624b101bbf)

**Comment by uglyp** [comment]
最新稳定版的开发者工具

**Comment by yang1206** [comment]
移除 main.ts引入的 corejs和相关依赖，uni-use依赖了 corejs, 引入corejs在支付宝小程序会编译错误

**Comment by yang1206** [comment]
> 最新稳定版的开发者工具

移除 main.ts引入的 corejs和相关依赖，uni-use依赖了 corejs, 引入corejs在支付宝小程序会编译错误

**Comment by uglyp** [comment]
感谢
