### ISSUE TITLE
初始化之后，微信开发工具打开没问题，真机模拟有问题

### ISSUE THREAD

**Issue by zwhGithub** [yang1206/uniapp-template#89]
初始化之后，微信开发工具打开没问题，真机模拟有问题

**Comment by zwhGithub** [comment]
![image](https://github.com/yang1206/uniapp-template/assets/19305956/2d1bcbf7-cd0d-4246-b028-74da60d7d221)

**Comment by yang1206** [comment]
已修复

**Comment by zy499** [comment]
安卓启动后不显示界面
